### PR TITLE
feat: breakpoint css

### PR DESCRIPTION
**Pull request by nasreddineskandrani**
## Description
The template todo has breakpoints at `1600px` `9XXpx` ... 

What do you think should we follow the template breakpoints exactly or change based on these articles?
and approximat behavior to the nearest new bp we pick???

article1 : https://medium.freecodecamp.org/the-100-correct-way-to-do-css-breakpoints-88d6a5ba1862
article2: https://jsramblings.com/2018/02/04/styled-components-media-queries.html

### CODE REVIEW

**Comment by aminpaks** [comment]
Let's keep this open, we focus on desktop for now. Once the first version is ready we'll continue this discussion.

**Comment by nasreddineskandrani** [comment]
As discussed in slack, it's important to set them since some dev may want to deliver full ready components at first time to don't go with a solution that doesn't scale for mobile and have to double redo the work later. Inforcing the mobile and all breakpoints in the first place allow people to code responsive directly and learn to do it if not.

so let's try to set  the breakpoints and let dev decice how to deliver.

Article2 values 
```
@mixin for-phone-only {
  @media (max-width: 599px) { @content; }
}
@mixin for-tablet-portrait-up {
  @media (min-width: 600px) { @content; }
}
@mixin for-tablet-landscape-up {
  @media (min-width: 900px) { @content; }
}
@mixin for-desktop-up {
  @media (min-width: 1200px) { @content; }
}
@mixin for-big-desktop-up {
  @media (min-width: 1800px) { @content; }
}
```

VS 

Material-UI
```
xs, extra-small: 0px or larger
sm, small: 600px or larger
md, medium: 960px or larger
lg, large: 1280px or larger
xl, extra-large: 1920px or larger
```

**Comment by aminpaks** [comment]
@nasreddineskandrani sounds good. I don't think your changes are necessary. We can just modify the values in the theme.

**Comment by nasreddineskandrani** [comment]
i don't think breakpoints should be in the theme :P it's not affecting the theme of the app.
the theme is kinda a set of values of colors, font-face, logo/images path/size.... 
If we move a theme to a CMS? based on a customer we don't want to change the breakpoints.

**Comment by nasreddineskandrani** [comment]
humm maybe the theme can be per device... but i still feel that the breakpoints don't have a place in the theme. What do you think?

**Comment by aminpaks** [comment]
I think for this project it's ok to keep them in theme. Though I don't have any objections to keep them in a static file too. It's just an extra import.

**Comment by nasreddineskandrani** [comment]
we are going to add this to the theme:
```
phoneOnly: `(max-width: ${breakpoint.phoneOnly})`,
```
i do agree with the extra import so let's try to avoid it
but it means i add a css rule to the theme object?
i feel it's wrong
just having the value inside the theme doesn't allow us to avoid writing the `max-width` or `min-width` inside the components (edited) 
with the device file it's an extra import that allow us to do `@media ${device.phoneOnly}`

**Comment by aminpaks** [comment]
I think we can composition to build up the conditional, the following is just an idea of a class based:
```tsx
class mediaQuery {
  private min: number;
  private max: number;
  constructor(private breakpoints) { }
  setMinMax(min: number, max: number) {
    this.min = min;
    this.max = max;
  }
  get() {
    return `(min-width: ${this.min}px) and (max-width: ${this.max});
  }
}

const mediaQueryFactory = (breakpoints) => {
  return new mediaQuery(breakpoints);
}

// usage
const StyledContainer = styled.div`
  @media ${props => props.theme.mediaQuery().setMinMax(200, 400).get()} {
    display: inline-block;
  }
`;
```

**Comment by nasreddineskandrani** [comment]
By harasing amin all day via slack lol, he did let go for my proposal with his comment about warping also the @media in an util => we decided to use mediaquery `function`(s)

**Pull request merged**
